"use client";
import { useState } from "react";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis, CartesianGrid, Legend } from "recharts";
import { PageTitle } from "@/components/page-title";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { useAdminAccess } from "@/components/admin-access";
import { getOverview } from "@/lib/operations-api";
import { apiError } from "@/lib/utils";
const duration = (ms: number | null) => ms === null ? "No data" : ms < 60000 ? `${Math.round(ms / 1000)} sec` : `${Math.round(ms / 60000)} min`;
function Metric({ label, value, detail, href }: { label: string; value: string | number; detail?: string; href?: string }) {
 const content = <><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p>{detail && <p className="mt-2 text-xs text-slate-500">{detail}</p>}</>;
 return href ? <Link href={href} className="rounded-xl border bg-white p-5 shadow-sm hover:border-[#a48734]">{content}<p className="mt-3 text-xs text-[#9d8034]">View details</p></Link> : <div className="rounded-xl border bg-white p-5 shadow-sm">{content}</div>;
}
export default function DashboardPage() {
 const [days, setDays] = useState(30); const access = useAdminAccess();
 const query = useQuery({ queryKey: ["operational-overview", days], queryFn: () => getOverview(days), refetchInterval: 60000 }); const s = query.data;
 const link = (permission: string, href: string) => access.can(permission) ? href : undefined;
 return <><PageTitle action={<div className="flex gap-2"><select aria-label="Reporting period" className="rounded-lg border bg-white px-3" value={days} onChange={e => setDays(Number(e.target.value))}>{[7,30,90].map(d => <option key={d} value={d}>Last {d} days</option>)}</select><Button variant="outline" disabled={query.isFetching} onClick={() => query.refetch()}>Refresh</Button></div>}>Operations overview</PageTitle>
 {query.isError && <p role="alert" className="mb-5 rounded bg-red-50 p-4 text-red-700">{apiError(query.error)}</p>}
 {query.isLoading && <div className="grid gap-4 md:grid-cols-4">{Array.from({length:8},(_,i)=><Skeleton key={i} className="h-36"/>)}</div>}
 {s && <div className="space-y-6"><p className="text-sm text-slate-500">Updated {new Date(s.generatedAt).toLocaleTimeString()} ? Reporting dates use UTC ? Tracking starts {s.trackingStartedAt ? new Date(s.trackingStartedAt).toLocaleDateString() : "with the first recorded event"}.</p>
 <section className="rounded-xl border border-amber-200 bg-amber-50 p-5"><h2 className="mb-4 text-lg font-bold">Needs attention</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Open panic alerts" value={s.panics.open} href={link("alerts:read","/alerts?group=panic&status=unresolved")}/><Metric label="Critical events" value={s.alerts.risk.find(r=>r._id==="critical")?.count||0} href={link("alerts:read","/alerts?severity=critical&status=unresolved")}/><Metric label="High / elevated events" value={`${s.alerts.risk.find(r=>r._id==="high")?.count||0} / ${s.alerts.risk.find(r=>r._id==="elevated")?.count||0}`} href={link("alerts:read","/alerts?status=unresolved")}/><Metric label="Open cases" value={s.cases.open} href={link("cases:read","/cases?status=unresolved")}/></div></section>
 <section><h2 className="mb-3 text-lg font-bold">Users and linked accounts</h2><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Registered users" value={s.users.total} href={link("users:read","/users")}/><Metric label="Active daily / weekly / monthly" value={`${s.users.dau} / ${s.users.wau} / ${s.users.mau}`} detail="Distinct authenticated users over calendar days" href={link("events:read","/events?kind=activity")}/><Metric label="New today / 7 days / 30 days" value={`${s.users.newToday} / ${s.users.new7} / ${s.users.new30}`} href={link("users:read",`/users?from=${new Date(new Date(s.generatedAt).getTime()-30*86400000).toISOString()}`)}/><Metric label="Email verified" value={`${s.users.emailVerified} (${s.users.emailVerifiedPercent}%)`} href={link("users:read","/users?verified=true")}/><Metric label="KYC completed" value={`${s.users.kycVerified} (${s.users.kycVerifiedPercent}%)`} href={link("users:read","/users?kyc=completed")}/><Metric label="Users with active bank records" value={`${s.accounts.bankLinkedUsers} (${s.accounts.bankLinkedPercent}%)`} detail="Linked records; live bank connectivity is not confirmed" href={link("users:read","/users?linked=true")}/><Metric label="Active linked account records" value={s.accounts.active} href={link("accounts:read","/accounts")}/><Metric label="Panic activations today" value={s.panics.today} href={link("events:read",`/events?kind=panic&from=${s.generatedAt.slice(0,10)}`)}/></div></section>
 <section><h2 className="mb-3 text-lg font-bold">Security and response</h2><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Alerts today / 7 days / 30 days" value={`${s.alerts.today} / ${s.alerts.last7} / ${s.alerts.last30}`} href={link("alerts:read","/alerts")}/><Metric label="Protective interventions" value={s.protectiveActions} detail={`Last ${days} days; app-level actions`} href={link("events:read",`/events?kind=protective_action&from=${s.from}`)}/><Metric label="False positives" value={`${s.alerts.falsePositive} (${s.alerts.falsePositiveRate}%)`} detail={`Of ${s.alerts.reviewed} reviewed alerts in period`} href={link("alerts:read",`/alerts?verdict=false_positive&from=${s.from}`)}/><Metric label="Average operator response" value={duration(s.alerts.averageResponseMs)} detail={`${s.alerts.responseSampleCount} alerts with an operator action`} href={link("alerts:read","/alerts")}/><Metric label="Cases resolved" value={s.cases.resolved} detail={`Last ${days} days`} href={link("cases:read",`/cases?status=resolved&resolvedFrom=${s.from}`)}/></div></section>
 <section className="rounded-xl border bg-white p-5"><h2 className="text-lg font-bold">Platform activity over time</h2><div className="mt-5 h-80"><ResponsiveContainer width="100%" height="100%"><LineChart data={s.trends}><CartesianGrid strokeDasharray="4 4"/><XAxis dataKey="date" tickFormatter={v=>String(v).slice(5)}/><YAxis allowDecimals={false}/><Tooltip/><Legend/>{[["newUsers","New users","#a48734"],["activeUsers","Active users","#0e7490"],["alerts","Alerts","#dc2626"],["panics","Panics","#9333ea"],["confirmed","Confirmed incidents","#be123c"],["protective","Interventions","#16a34a"],["resolvedCases","Resolved cases","#475569"]].map(([key,name,color])=><Line key={key} dataKey={key} name={name} stroke={color} dot={false} strokeWidth={2}/>)}</LineChart></ResponsiveContainer></div></section>
 <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-xl border bg-white p-5"><h2 className="mb-4 text-lg font-bold">Users by bank</h2>{s.accounts.banks.map(b=><div key={b.bank} className="flex justify-between border-b py-3 text-sm"><span>{b.bank||"Unknown bank"}</span>{access.can("users:read")?<Link className="text-[#9d8034] underline" href={`/users?bank=${encodeURIComponent(b.bank)}`}>{b.users} users ? {b.accounts} accounts</Link>:<span>{b.users} users ? {b.accounts} accounts</span>}</div>)}{!s.accounts.banks.length&&<p className="text-sm text-slate-500">No active bank records.</p>}</section><section className="rounded-xl border bg-white p-5"><h2 className="mb-4 text-lg font-bold">Verification usage and sources</h2>{["email","phone","website","account"].map(tool=><div key={tool} className="flex justify-between border-b py-3 text-sm"><span className="capitalize">{tool}</span>{access.can("events:read")?<Link className="text-[#9d8034] underline" href={`/events?kind=verification_lookup&tool=${tool}&from=${s.from}`}>{s.verification.usage.find(u=>u._id===tool)?.count||0} checks</Link>:<span>{s.verification.usage.find(u=>u._id===tool)?.count||0} checks</span>}</div>)}<p className="mt-4 text-sm text-slate-500">{s.verification.sources.map(source=>`${source._id}: ${source.count}`).join(" ? ")||"No lookup events yet."}</p></section></div>
 <section><h2 className="mb-3 text-lg font-bold">Learning engagement</h2><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Completed / incomplete quizzes" value={`${s.learning.completed} / ${s.learning.incomplete}`} detail="Tracked quiz versions; opened but not submitted" href={link("learning:read","/learning")}/><Metric label="Average quiz completion time" value={duration(s.learning.averageDurationMs)} detail="First recorded quiz open to first submission"/><Metric label="Users answering additional questions" value={s.learning.additionalQuestionUsers} detail="Users who retried a completed quiz"/><Metric label="Submissions in period" value={s.learning.attempts} href={link("learning:read","/learning")}/></div><div className="mt-4 rounded-xl border bg-white p-5"><h3 className="font-semibold">Most popular learning materials</h3>{s.learning.popular.map(p=><p key={p._id} className="mt-3 text-sm">{p.title} <span className="text-slate-500">? {p.users} users ? {p.attempts} attempts</span></p>)}{!s.learning.popular.length&&<p className="mt-3 text-sm text-slate-500">No submissions in this period.</p>}</div></section>
 <section className="rounded-xl border bg-white p-5"><h2 className="mb-4 text-lg font-bold">Availability samples</h2><div className="grid gap-4 sm:grid-cols-3">{s.availability.map(service=><Metric key={service.service} label={service.service} value={`${service.percent}%`} detail={`${service.samples} checks`} href={link("health:read","/health")}/>)}</div><p className="mt-4 text-xs text-slate-500">In-process sampling cannot measure outages while the server is stopped. External monitoring is needed for complete coverage.</p></section>
 </div>}</>;
}
