"use client";
import { useQuery } from "@tanstack/react-query";
import { OperationDialog } from "./operation-dialog";
import { getUserOverview } from "@/lib/operations-api";
import { apiError, formatDate } from "@/lib/utils";
export function UserOverview({ id, onClose }: { id: string; onClose: () => void }) {
  const query=useQuery({queryKey:["user-overview",id],queryFn:()=>getUserOverview(id)}); const s=query.data;
  const age=s?.age ?? null;
  return <OperationDialog title="User overview" open onClose={onClose}>{query.isLoading&&<p>Loading user...</p>}{query.isError&&<p role="alert" className="text-red-700">{apiError(query.error)}</p>}{s&&<div className="space-y-5"><div className="grid gap-3 rounded bg-slate-50 p-4 text-sm sm:grid-cols-2"><p>Name: {s.user.name||"—"}</p><p>Email: {s.user.email}</p><p>Phone: {s.user.phone||"—"}</p><p>Age: {age===null?"Not provided":age}</p><p>Profession: {s.user.profession||"Not provided"}</p><p>Location: {[s.user.city,s.user.country].filter(Boolean).join(", ")||"Not provided"}</p><p>Active linked accounts: {s.accountCount}</p><p>Email: {s.user.verificationInfo?.verified?"Verified":"Unverified"} · KYC: {s.user.kyc?.status||"not_started"}</p></div><section><h3 className="font-semibold">Linked account records</h3>{s.accounts.map(a=><p key={a._id} className="mt-2 text-sm">{a.bankName||a.accountType} · {a.nickname} · {a.isLocked?"Locked":"Active"} {a.lockedReason}</p>)}{!s.accounts.length&&<p className="mt-2 text-sm text-slate-500">No account details available.</p>}</section><section><h3 className="font-semibold">Recent alerts</h3>{s.alerts.map(a=><p key={a._id} className="mt-2 text-sm">{a.title} · {a.severity} · {a.status} · {formatDate(a.createdAt)}</p>)}</section><section><h3 className="font-semibold">Cases</h3>{s.cases.map(c=><div key={c._id} className="mt-2 rounded border p-3 text-sm"><p>{c.title} · {c.status}</p>{c.resolution&&<p className="mt-2">Resolution: {c.resolution}</p>}</div>)}</section><section><h3 className="font-semibold">SOS history</h3>{s.emergencies.map(e=><p key={e._id} className="mt-2 text-sm">{e.status} · Activated {formatDate(e.activatedAt)} {e.resolvedAt&&`· Resolved ${formatDate(e.resolvedAt)} by ${e.clearedByRole}`}</p>)}{!s.emergencies.length&&<p className="mt-2 text-sm text-slate-500">No SOS history.</p>}</section></div>}</OperationDialog>;
}
